site_name: DLMS.dev
site_description: 'Resources for the python library `dlms-cosem` and general DLMS/COSEM'
site_author: 'Henrik Palmlund Wahlgren @ Utilitarian'

nav:
  - Home: index.md
  - About DLMS/COSEM: dlms_cosem.md
  - Getting Started:
      - Connect to your meter: connect_to_your_meter.md


theme:
  name: material


copyright: 'Copyright &copy; 2020-2021 Palmlund Wahlgren Innovative Technology AB'

repo_url: https://github.com/pwitab/dlms-cosem
repo_name: pwitab/dlms-cosem


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: '#'
  - def_list
